# Generated by Django 4.1 on 2022-08-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='covid_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=70)),
                ('CountryCode', models.CharField(max_length=10)),
                ('newConfirmed', models.IntegerField()),
                ('TotalConfirmed', models.IntegerField()),
                ('NewDeaths', models.IntegerField()),
                ('TotalDeaths', models.IntegerField()),
                ('NewRecovered', models.IntegerField()),
                ('TotalRecovered', models.IntegerField()),
                ('Date', models.DateTimeField()),
            ],
        ),
    ]
